var weapons = {
    club: {prof: 2, damage: '1d6', range: 1, price: 1, weight: 3, group: 'mace', properties: [], hands: 'one', category: ['simple', 'melee']},
    dagger: {prof: 3, damage: '1d4', range: [5, 10], price: 1, weight: 1, group: 'light blade', properties: ['off-hand', 'light thrown'], hands: 'one', category: ['simple', 'melee']},
    javelin: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    mace: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    sickle: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    spear: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    greatclub: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    morningstar: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    quarterstaff: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    scythe: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    battleaxe: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    flail: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    handaxe: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    longsword: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    scimitar: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    shortsword: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    throwinghammer: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    warhammer: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    warpick: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    falchion: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    glaive: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    greataxe: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    greatsword: {prof: 3, damage: '1d10', range: 1, price: 30, weight: 12, group: 'heavy blade', properties: [], hands: 'two', category: ['military', 'melee']},
    halberd: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    heavyflail: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    longspear: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    maul: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    bastardsword: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    katar: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    rapier: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    spikedchain: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    //ranged
    handcrossbow: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    sling: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    crossbow: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    longbow: {prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''},
    shortbow: {prof: 2, damage: '1d8', range: [15, 30], price: 25, weight: 2, group: 'bow', properties: ['load free', 'small'], hands: 'two', category: ['military', 'ranged']},
    shuriken: {prof: 0, damage: '', range: [6, 12], price: 0, weight: 0, group: '', properties: [], hands: ''}, 
    unarmed: {damage: '1d4', type: 'melee', group: 'unarmed'}
};
//prof: 0, damage: '', range: 1, price: 0, weight: 0, group: '', properties: [], hands: ''